# Generated by Django 5.2.15 on 2026-06-17 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatgroup_groupmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgroup',
            name='group_photo',
            field=models.ImageField(blank=True, null=True, upload_to='group_photos/'),
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
