# Generated by Django 5.2.15 on 2026-06-18 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatgroup_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
